version: '3.6'
services:
  iris:
    environment:
      - OPENAPI_KEY=${OPENAPI_KEY}
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false --ISCAgent false
    ports:
      - 1972
      - 52797:52773
      - 53773
    volumes:
      - ./:/home/irisowner/dev/

